//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje2_MuzikSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kisiler
    {
        public short ID { get; set; }
        public string ADSOYAD { get; set; }
        public string TELEFON { get; set; }
        public string MAIL { get; set; }
        public string ENSTRUMAN { get; set; }
        public string GUN { get; set; }
    }
}
