//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje18_RegisterForm.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Register
    {
        public int ID { get; set; }
        public string ISIM { get; set; }
        public string MAIL { get; set; }
        public string KULLANICIAD { get; set; }
        public string SIFRE { get; set; }
    }
}
