// <auto-generated />
namespace EntityCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreateMÜsteriSEHIRColumnInMusterilersTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateMÜsteriSEHIRColumnInMusterilersTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202204232129091_CreateMÜsteriSEHIRColumnInMusterilersTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
